[server]
headless = true
fileWatcherType = "none" # <--- THIS FIXES THE CRASH
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[runner]
magicEnabled = false
